name: Detect clones

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: write

jobs:
  clone-detection:
    runs-on: ubuntu-latest
    environment: main
    env: 
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout query repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: query_repo

      - name: checkout clone detection repo
        uses: actions/checkout@v4
        with:
          repository: TrishKedi/cdd-ci
          ref: task/restructure
          path: clone_detection_repo

      - name: Install python
        uses: actions/setup-python@v5

      - name: Setup Review Dog
        uses: reviewdog/action-setup@v1
        
      - name: Install dependencies
        working-directory: clone_detection_repo
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Get changed files
        working-directory: query_repo
        run: |
          git fetch origin "${{ github.base_ref }}" --depth=1
          git diff --name-only "origin/${{ github.base_ref }}...HEAD" -- '*.js' > changed_files.txt
          echo "Changed files:"
          cat changed_files.txt

      - name: Search for clones 
        working-directory: query_repo
        run: |
          python ../clone_detection_repo/src/app.py \
          --changed-files changed_files.txt \
          --candidate-repo code-samples-ui 

      - name: Comment with reviewdog
        working-directory: query_repo
        run: |
          cat ../clone_detection_repo/data/exports/diagnostics.json \
          | reviewdog -f=rdjson -reporter=github-pr-review -level=warning -filter-mode=nofilter








